# Generated by Django 2.0 on 2020-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='compress_img',
            field=models.ImageField(blank=True, null=True, upload_to='compressimg'),
        ),
        migrations.AlterField(
            model_name='album',
            name='original_img',
            field=models.ImageField(blank=True, null=True, upload_to='originalimg'),
        ),
    ]
